services:
  app:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/home/ubuntu/website
      - /etc/pki/tls/private/diakhatepalme_com.key:/run/secrets/diakhatepalme_com_key
      - /etc/pki/tls/private/diakhatepalme_com.crt:/run/secrets/diakhatepalme_com_cert
    working_dir: /home/ubuntu/website
    tty: true
    stdin_open: true